Depi MVC/Controllers/CourseController.cs
using Depi_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Depi_MVC.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Index()
        {
            WebAppContext context = new WebAppContext();
            var courses = context.Courses.ToList();
            return View(courses);
        }
        public IActionResult Details(int id)
        {
            WebAppContext context = new WebAppContext();
            var courses = context.Courses.FirstOrDefault(x => x.Id == id);
            return View(courses);
        }
        [HttpGet]
        public IActionResult Add()
        {
           
            WebAppContext context = new WebAppContext();
            return View();
        }
        [HttpPost]
        public IActionResult Add(Course model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    WebAppContext context = new WebAppContext();
                    context.Courses.Add(model);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }catch (Exception ex)
            {
                ModelState.AddModelError("msg", ex.InnerException.Message);
            }
           
            return View(model);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {

            WebAppContext context = new WebAppContext();
            var course = context.Courses.FirstOrDefault(i => i.Id == id);
            return View(course);
        }
        [HttpPost]
        public IActionResult Update(Course model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    WebAppContext context = new WebAppContext();
                    context.Courses.Update(model);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }catch(Exception ex)
            {
                ModelState.AddModelError("msg", ex.InnerException.Message);
            }
            
            return View(model);
        }
        [HttpGet]
        public IActionResult Remove(int id)
        {
            WebAppContext context = new WebAppContext();
            var model = context.Courses.FirstOrDefault(i => i.Id == id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Remove(Course model)
        {
            WebAppContext context = new WebAppContext();
            context.Courses.Remove(model);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult CheckDegree(int maxdegree,int minDegree)
        {
            if(maxdegree < minDegree)
            {
                return Json("The Max Degree Cannot Be Lower Than the Min Degree");
            }else if(maxdegree > 100) 
            {
                return Json(false);
            }
            return Json(true);
        }
        public IActionResult CheckMinDegree(int mindegree)
        {
            if (mindegree != 25)
            {
                return Json(false);
            }
            else
            {
                return Json(true);
            }
        }
    }
}

Depi MVC/Controllers/CourseResultController.cs
using Depi_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Depi_MVC.Controllers
{
    public class CourseResultController : Controller
    {
        public IActionResult Index()
        {
            WebAppContext context = new WebAppContext();
            var cs = context.CourseResults.ToList();
            return View(cs);
        }
        public IActionResult Details(int id)
        {
            WebAppContext context = new WebAppContext();
            var cs = context.CourseResults.FirstOrDefault(x => x.Id == id);
            return View(cs);
        }
        [HttpGet]
        public IActionResult Add()
        {
            WebAppContext context = new WebAppContext();
            ViewBag.Courses = context.Courses.ToList();
            ViewBag.Trainees = context.Trainees.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Add(CourseResults model)
        {
            WebAppContext context = new WebAppContext();
            ViewBag.Trainees = context.Trainees.ToList();
            ViewBag.Courses = context.Courses.ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    context.CourseResults.Add(model);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("msg", ex.InnerException.Message);
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            WebAppContext context = new WebAppContext();
            CourseResults cs = context.CourseResults.FirstOrDefault(i => i.Id == id);
            ViewBag.Courses = context.Courses.ToList();
            ViewBag.Trainees = context.Trainees.ToList();
            return View(cs);
        }
        [HttpPost]
        public IActionResult Update(CourseResults model)
        {
            WebAppContext context = new WebAppContext();
            ViewBag.Trainees = context.Trainees.ToList();
            ViewBag.Courses = context.Courses.ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    context.CourseResults.Update(model);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("msg", ex.InnerException.Message);
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Remove(int id)
        {
            WebAppContext context = new WebAppContext();
            CourseResults model = context.CourseResults.FirstOrDefault(i => i.Id == id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Remove(CourseResults model)
        {
            WebAppContext context = new WebAppContext();
            context.CourseResults.Remove(model);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Depi MVC/Controllers/DepartmentController.cs
using Depi_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Depi_MVC.Controllers
{
    public class DepartmentController : Controller
    {
        public IActionResult Index()
        {
            WebAppContext context = new WebAppContext();
            var departments = context.Departments.ToList();
            return View(departments);
        }
        public IActionResult Details(int id)
        {
            WebAppContext context = new WebAppContext();
            var department = context.Departments.FirstOrDefault(x => x.Id == id);
            return View(department);
        }
        [HttpGet]
        public IActionResult Add()
        {
            WebAppContext context = new WebAppContext();
            return View();
        }
        [HttpPost]
        public IActionResult Add(Department model)
        {
            WebAppContext context = new WebAppContext();
            if (model is not null)
            {
                context.Departments.Add(model);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            WebAppContext context = new WebAppContext();
            Department department = context.Departments.FirstOrDefault(i => i.Id == id);
            return View(department);
        }
        [HttpPost]
        public IActionResult Update(Department model)
        {
            WebAppContext context = new WebAppContext();
            if (model is not null)
            {
                context.Departments.Update(model);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Remove(int id)
        {
            WebAppContext context = new WebAppContext();
            Department model = context.Departments.FirstOrDefault(i => i.Id == id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Remove(Department model)
        {
            WebAppContext context = new WebAppContext();
            context.Departments.Remove(model);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Depi MVC/Controllers/InstructorController.cs
using Depi_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Depi_MVC.Controllers
{
    public class InstructorController : Controller
    {
        //Instructor/Index

        public IActionResult Index()
        {
            WebAppContext context = new WebAppContext();
            var instructors = context.Instructors.ToList();
            return View(instructors);
        }
        public IActionResult Details(int id)
        {
            WebAppContext context = new WebAppContext();
            var instructor = context.Instructors.FirstOrDefault(x => x.Id == id);
            return View(instructor);
        }
        [HttpGet]
        public IActionResult Add()
        {
            WebAppContext context = new WebAppContext();
            ViewBag.Courses = context.Courses.ToList();
            ViewBag.Departments = context.Departments.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Add(Instructor model)
        {
            WebAppContext context = new WebAppContext();
            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();
            if (model is not null)
            {
                context.Instructors.Add(model);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            WebAppContext context = new WebAppContext();
            Instructor instructor = context.Instructors.FirstOrDefault(i => i.Id == id);
            ViewBag.Courses = context.Courses.ToList();
            ViewBag.Departments = context.Departments.ToList();
            return View(instructor);
        }
        [HttpPost]
        public IActionResult Update(Instructor model)
        {
            WebAppContext context = new WebAppContext();
            ViewBag.Departments = context.Departments.ToList();
            ViewBag.Courses = context.Courses.ToList();
            if (model is not null)
            {
                context.Instructors.Update(model);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Remove(int id)
        {
            WebAppContext context = new WebAppContext();
            Instructor model = context.Instructors.FirstOrDefault(i=>i.Id == id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Remove(Instructor model)
        {
            WebAppContext context = new WebAppContext();
            context.Instructors.Remove(model);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Depi MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Depi_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Depi_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Depi_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                        </li>
                        </li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        </li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="CourseResult" asp-action="Index">CoursesResults</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Depi_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>